name: dilbert
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_2
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1m=h7f8727e_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py39h06a4308_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - charset-normalizer==2.0.11
    - click==8.0.3
    - faiss-cpu==1.7.2
    - filelock==3.4.2
    - huggingface-hub==0.4.0
    - idna==3.3
    - joblib==1.1.0
    - nltk==3.6.7
    - numpy==1.22.2
    - packaging==21.3
    - pandas==1.4.0
    - pillow==9.0.1
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2022.1.18
    - requests==2.27.1
    - sacremoses==0.0.47
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sentence-transformers==2.1.0
    - sentencepiece==0.1.96
    - six==1.16.0
    - threadpoolctl==3.1.0
    - tokenizers==0.11.4
    - torch==1.10.2
    - torchvision==0.11.3
    - tqdm==4.62.3
    - transformers==4.16.2
    - typing-extensions==4.0.1
    - urllib3==1.26.8
